# Generated by Django 6.1.2 on 2026-10-08 08:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('admission_type', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('OPD', 'OPD Referral'), ('ELECTIVE', 'Elective'), ('TRANSFER', 'Transfer'), ('OTHER', 'Other')], default='OPD', max_length=20)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason_for_admission', models.TextField(blank=True)),
                ('provisional_diagnosis', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ADMITTED', 'Admitted'), ('ON_HOLD', 'On Hold'), ('DISCHARGED', 'Discharged'), ('CANCELLED', 'Cancelled')], default='ADMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_admissions', to='hospitals.bed')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ipd_admissions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_admissions', to='hospitals.department')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='ipd_admissions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_admissions', to='patients.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_admissions', to='hospitals.room')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_admissions', to='hospitals.ward')),
            ],
            options={
                'ordering': ['-admission_date', '-id'],
            },
        ),
    ]
