# Generated by Django 6.1.2 on 2026-10-08 08:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('ipd', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDBedTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_transfers', to='ipd.ipdadmission')),
                ('from_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipd_transfers_from_bed', to='hospitals.bed')),
                ('from_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipd_transfers_from_room', to='hospitals.room')),
                ('from_ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ipd_transfers_from_ward', to='hospitals.ward')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_bed_transfers', to='patients.patient')),
                ('to_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_transfers_to_bed', to='hospitals.bed')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_transfers_to_room', to='hospitals.room')),
                ('to_ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_transfers_to_ward', to='hospitals.ward')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_ipd_bed_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-transfer_date', '-id'),
            },
        ),
    ]
