# Generated by Django 6.1.2 on 2026-10-08 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0002_ipdbedtransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDDoctorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary / Attending Doctor'), ('CONSULTANT', 'Consulting Doctor')], default='CONSULTANT', max_length=20)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_assignments', to='ipd.ipdadmission')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ipd_doctors', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='ipd_doctor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-assigned_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='IPDDoctorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note_type', models.CharField(default='Progress Note', max_length=50)),
                ('clinical_note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_notes', to='ipd.ipdadmission')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='ipd_doctor_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-note_date', '-id'),
            },
        ),
    ]
