# Generated by Django 6.1.2 on 2026-10-09 06:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipd', '0001_initial'),
        ('opd', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '01. Lab Category',
                'verbose_name_plural': '01. Lab Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '05. Lab Package',
                'verbose_name_plural': '05. Lab Packages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '02. Sample Type',
                'verbose_name_plural': '02. Sample Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('SAMPLE_PENDING', 'Sample Pending'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('PROCESSING', 'Processing'), ('PARTIAL', 'Partially Completed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('clinical_notes', models.TextField(blank=True)),
                ('priority', models.BooleanField(default=False, help_text='Mark as urgent/stat laboratory order.')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_orders', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_lab_orders', to=settings.AUTH_USER_MODEL)),
                ('ipd_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='ipd.ipdadmission', verbose_name='IPD Admission')),
                ('opd_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='opd.opdvisit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='patients.patient')),
            ],
            options={
                'verbose_name': '07. Lab Order',
                'verbose_name_plural': '07. Lab Orders',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('TEST', 'Test'), ('PACKAGE', 'Package')], default='TEST', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('SAMPLE_PENDING', 'Sample Pending'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.laborder')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='laboratory.labpackage')),
            ],
            options={
                'verbose_name': '08. Lab Order Item',
                'verbose_name_plural': '08. Lab Order Items',
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('VERIFIED', 'Verified'), ('FINAL', 'Final'), ('AMENDED', 'Amended'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('clinical_summary', models.TextField(blank=True)),
                ('report_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_lab_reports', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='laboratory.laborder')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_reports', to='patients.patient')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_lab_reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_lab_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '11. Lab Report',
                'verbose_name_plural': '11. Lab Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='LabSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected'), ('PROCESSED', 'Processed')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_lab_samples', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='laboratory.laborder')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='laboratory.laborderitem')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_lab_samples', to=settings.AUTH_USER_MODEL)),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='laboratory.sampletype')),
            ],
            options={
                'verbose_name': '09. Lab Sample',
                'verbose_name_plural': '09. Lab Samples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('result_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('TEXT', 'Text'), ('POSITIVE_NEGATIVE', 'Positive / Negative'), ('CHOICE', 'Choice')], default='NUMERIC', max_length=30)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('specimen_volume', models.CharField(blank=True, max_length=50)),
                ('methodology', models.CharField(blank=True, max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('turnaround_time_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='laboratory.labcategory')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='laboratory.sampletype')),
            ],
            options={
                'verbose_name': '03. Lab Test',
                'verbose_name_plural': '03. Lab Tests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(blank=True, max_length=500)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=255)),
                ('interpretation', models.TextField(blank=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ENTERED', 'Entered'), ('VERIFIED', 'Verified'), ('AMENDED', 'Amended'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_lab_results', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='laboratory.laborderitem')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_lab_results', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='laboratory.labsample')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='laboratory.labtest')),
            ],
            options={
                'verbose_name': '10. Lab Result',
                'verbose_name_plural': '10. Lab Results',
                'ordering': ['test__name'],
            },
        ),
        migrations.CreateModel(
            name='LabReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('ALL', 'All'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='ALL', max_length=10)),
                ('age_min', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('age_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('normal_min', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('normal_max', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('critical_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('critical_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('normal_text', models.CharField(blank=True, max_length=255)),
                ('interpretation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='laboratory.labtest')),
            ],
            options={
                'verbose_name': '04. Reference Range',
                'verbose_name_plural': '04. Reference Ranges',
                'ordering': ['test', 'age_min'],
            },
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='laboratory.labtest'),
        ),
        migrations.CreateModel(
            name='LabPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.labpackage')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_items', to='laboratory.labtest')),
            ],
            options={
                'verbose_name': '06. Lab Package Item',
                'verbose_name_plural': '06. Lab Package Items',
                'constraints': [models.UniqueConstraint(fields=('package', 'test'), name='unique_lab_package_test')],
            },
        ),
    ]
