# Generated by Django 6.1.2 on 2026-10-06 18:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('appointment_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('token_number', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('appointment_type', models.CharField(choices=[('NEW', 'New Consultation'), ('FOLLOW_UP', 'Follow-up'), ('EMERGENCY', 'Emergency'), ('PROCEDURE', 'Procedure'), ('REVIEW', 'Review')], default='NEW', max_length=20)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('IN_CONSULTATION', 'In Consultation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='BOOKED', max_length=25)),
                ('booking_source', models.CharField(choices=[('RECEPTION', 'Reception'), ('ONLINE', 'Online'), ('PHONE', 'Phone'), ('WALK_IN', 'Walk-in'), ('REFERRAL', 'Referral')], default='RECEPTION', max_length=20)),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='hospitals.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.doctorschedule')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['appointment_date', 'start_time', 'token_number'],
                'indexes': [models.Index(fields=['appointment_date', 'doctor'], name='appointment_appoint_c5b3da_idx'), models.Index(fields=['appointment_date', 'department'], name='appointment_appoint_0f77b6_idx'), models.Index(fields=['patient', 'appointment_date'], name='appointment_patient_8037cd_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'appointment_date', 'start_time'), name='unique_doctor_appointment_slot'), models.UniqueConstraint(fields=('doctor', 'appointment_date', 'token_number'), name='unique_doctor_daily_token')],
            },
        ),
    ]
