# Generated by Django 6.1.2 on 2026-10-07 10:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OPDVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('visit_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('VITALS_COMPLETED', 'Vitals Completed'), ('IN_CONSULTATION', 'In Consultation'), ('CONSULTATION_COMPLETED', 'Consultation Completed'), ('REFERRED', 'Referred'), ('ADMITTED', 'Admitted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='WAITING', max_length=30)),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opd_visit', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opd_visits', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opd_visits', to='hospitals.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opd_visits', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opd_visits', to='patients.patient')),
            ],
            options={
                'verbose_name': 'OPD Visit',
                'verbose_name_plural': 'OPD Visits',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OPDFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField(db_index=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opd_followups', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opd_followups', to='patients.patient')),
                ('opd_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='opd.opdvisit')),
            ],
            options={
                'verbose_name': 'OPD Follow-up',
                'verbose_name_plural': 'OPD Follow-ups',
                'ordering': ['followup_date'],
            },
        ),
        migrations.CreateModel(
            name='OPDDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_type', models.CharField(choices=[('PRIMARY', 'Primary Diagnosis'), ('SECONDARY', 'Secondary Diagnosis'), ('DIFFERENTIAL', 'Differential Diagnosis'), ('PROVISIONAL', 'Provisional Diagnosis')], default='PRIMARY', max_length=20)),
                ('diagnosis', models.CharField(max_length=255)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opd_diagnoses', to='doctors.doctor')),
                ('opd_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='opd.opdvisit')),
            ],
            options={
                'verbose_name': 'OPD Diagnosis',
                'verbose_name_plural': 'OPD Diagnoses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OPDConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('clinical_findings', models.TextField(blank=True, null=True)),
                ('examination', models.TextField(blank=True, null=True)),
                ('diagnosis_summary', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
                ('consultation_start', models.DateTimeField(blank=True, null=True)),
                ('consultation_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opd_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='opd.opdvisit')),
            ],
            options={
                'verbose_name': 'OPD Consultation',
                'verbose_name_plural': 'OPD Consultations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in °F', max_digits=4, null=True)),
                ('systolic_bp', models.PositiveIntegerField(blank=True, help_text='Systolic blood pressure', null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, help_text='Diastolic blood pressure', null=True)),
                ('pulse_rate', models.PositiveIntegerField(blank=True, help_text='Pulse rate per minute', null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='Respiratory rate per minute', null=True)),
                ('spo2', models.DecimalField(blank=True, decimal_places=2, help_text='Oxygen saturation percentage', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=6, null=True)),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=2, help_text='Blood glucose', max_digits=6, null=True)),
                ('pain_score', models.PositiveIntegerField(blank=True, help_text='Pain score from 0 to 10', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opd_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='opd.opdvisit')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_patient_vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Vital',
                'verbose_name_plural': 'Patient Vitals',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='opdvisit',
            index=models.Index(fields=['visit_date', 'status'], name='opd_opdvisi_visit_d_c23c58_idx'),
        ),
        migrations.AddIndex(
            model_name='opdvisit',
            index=models.Index(fields=['patient', 'visit_date'], name='opd_opdvisi_patient_2bbbdc_idx'),
        ),
        migrations.AddIndex(
            model_name='opdvisit',
            index=models.Index(fields=['doctor', 'visit_date'], name='opd_opdvisi_doctor__608933_idx'),
        ),
        migrations.AddIndex(
            model_name='opdfollowup',
            index=models.Index(fields=['followup_date', 'status'], name='opd_opdfoll_followu_1cd642_idx'),
        ),
        migrations.AddIndex(
            model_name='opdfollowup',
            index=models.Index(fields=['patient', 'followup_date'], name='opd_opdfoll_patient_4c2bb1_idx'),
        ),
    ]
